const shell=(title,body)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${title}</title><style>:root{--bg:#070707;--panel:#121316;--line:#34363b;--text:#f4f4f4;--muted:#a7aab0;--red:#b31f2a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#251014,#08090a 42%,#050506);color:var(--text);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.65}.wrap{max-width:900px;margin:0 auto;padding:28px 18px 60px}.nav{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px}.brand{text-decoration:none;color:#fff;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.links{display:flex;gap:10px;flex-wrap:wrap}.links a{color:#ddd;text-decoration:none;border:1px solid #3a3d43;border-radius:9px;padding:8px 11px;background:#111216}.card{background:linear-gradient(180deg,#151619,#101113);border:1px solid var(--line);border-radius:20px;padding:28px}.badge{display:inline-block;border:1px solid #4a4c52;border-radius:999px;padding:5px 9px;color:#d1d2d5;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.muted{color:var(--muted)}h1{font-size:clamp(34px,7vw,58px);line-height:1;margin:12px 0 14px}h2{margin-top:30px}a{color:#e7a6ab}ul{padding-left:22px}.footer{margin-top:24px;color:#777;text-align:center;font-size:13px}</style></head><body><div class="wrap"><nav class="nav"><a class="brand" href="/">MisfitMafia Bot</a><div class="links"><a href="/">Home</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></nav><main class="card">${body}</main><div class="footer">MisfitMafia Bot • YouTube membership verification for Discord communities</div></div></body></html>`;

export function registerLegalRoutes(app){
  app.get('/privacy',(_req,res)=>res.send(shell('Privacy Policy — MisfitMafia Bot',`
    <span class="badge">Legal</span><h1>Privacy Policy</h1><p class="muted">Last updated: August 7, 2026</p>
    <p>MisfitMafia Bot provides YouTube membership verification and Discord role assignment for participating communities. This policy explains what information the service uses and why.</p>
    <h2>Information we process</h2><ul><li>Discord account identifiers, username/display name, and your connected YouTube channel identifier when you choose to verify.</li><li>YouTube creator authorization tokens for creators who explicitly connect their channel.</li><li>YouTube membership status and membership level information needed to determine the correct Discord role.</li><li>Operational records such as verification timestamps, sync status, and limited error/audit information needed to maintain the service.</li></ul>
    <h2>How we use information</h2><p>Information is used only to link Discord and YouTube identities, verify eligible YouTube channel memberships, assign or remove Discord roles, perform membership audits, maintain grace periods, and operate the service.</p>
    <h2>Google API data</h2><p>MisfitMafia Bot uses Google and YouTube APIs only for the functionality described above. Google user data obtained through OAuth is not sold, used for advertising, or shared for unrelated purposes.</p>
    <h2>Retention</h2><p>Verification and membership records may be retained while needed to provide role synchronization and grace-period functionality. Creator OAuth credentials remain stored while the creator connection is active. Records may be deleted when a creator or linked account is removed from the service, subject to operational backup retention.</p>
    <h2>Security</h2><p>OAuth credentials and service secrets are kept server-side and are not displayed to viewers. Access to administrative functions is restricted.</p>
    <h2>Your choices</h2><p>You can stop using the service at any time. Creators may revoke Google access from their Google Account permissions. Discord users may disconnect their YouTube account from Discord, although doing so may prevent future verification.</p>
    <h2>Contact</h2><p>For privacy or deletion requests, contact the MisfitMafia Bot administrator through the community where you use the service.</p>
  `)));

  app.get('/terms',(_req,res)=>res.send(shell('Terms of Service — MisfitMafia Bot',`
    <span class="badge">Legal</span><h1>Terms of Service</h1><p class="muted">Last updated: August 7, 2026</p>
    <p>By using MisfitMafia Bot, you agree to these Terms of Service.</p>
    <h2>Service purpose</h2><p>MisfitMafia Bot connects Discord identities with YouTube membership information so participating communities can verify memberships and assign Discord roles.</p>
    <h2>Eligibility and authorization</h2><p>You may only connect accounts and YouTube channels that you are authorized to use. Creators connecting a channel must have authority to grant the requested YouTube API permissions.</p>
    <h2>Acceptable use</h2><p>You may not attempt to bypass verification, impersonate another user or creator, interfere with the service, abuse OAuth flows, scrape protected data, or use the service for unlawful purposes.</p>
    <h2>Third-party services</h2><p>The service relies on Discord, Google, YouTube, Railway, and other infrastructure providers. Their respective terms and availability may affect the service.</p>
    <h2>No guarantee of uninterrupted service</h2><p>The service is provided on an as-available basis. Membership checks, role assignments, or audits may be delayed or unavailable because of API limits, account configuration, outages, or third-party changes.</p>
    <h2>Role and membership decisions</h2><p>Discord role assignment depends on information returned by connected services and the configuration selected by participating community administrators. The service does not itself sell or manage YouTube memberships.</p>
    <h2>Changes</h2><p>These terms may be updated as the service changes. Continued use after an update constitutes acceptance of the revised terms.</p>
    <h2>Contact</h2><p>Questions about these terms should be directed to the MisfitMafia Bot administrator through the community where you use the service.</p>
  `)));
}
